// client/src/components/Clients.jsx

import {gql,useQuery} from '@apollo/client'


const GET_CLIENTS = gql `

query getClients {
    clients{
        id
        name
        email
        phone
    }
}
`


export default function Clients() {
   const {loading,error,data} = useQuery(GET_CLIENTS)
if (loading) return <p>loading..</p>
if(error) return <p>Something went wrong</p>

  return (
    <>
    {!loading && !error && <h1>Clients</h1>}
    </>
  )
}

// client/src/Clients.svelte
<script>
 import { query, onMount } from 'svelte-apollo';
    import { gql } from 'graphql-tag';
    import { ApolloClient } from 'apollo-client';
    import { InMemoryCache } from 'apollo-cache-inmemory';
    import { HttpLink } from 'apollo-link-http';
  
    
    const client = new ApolloClient({
      link: new HttpLink({ uri: 'http://localhost:3000/graphql' }), 
      cache: new InMemoryCache(),
    });
  
     const GET_CLIENTS = gql`
         query{
           clients{
                 name
                 email
                 phone
    }
}
`

const { data: clients } = query(GET_CLIENTS, {}, client);



</script>
